# This is a basic workflow to help you get started with Actions

name: Nodejs setup express

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  installation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v5.0.0
  
    - name: Verify Node.js Installation
      run: node --version
  
    - name: Create Express App Structure
      run: |
        mkdir express-app
        cd express-app
        echo "console.log('Hello from Express App');" > index.js
        cat index.js
        

        
              

